// src/Ui/EmployeeMng/ReviewedDocsSection/constants/docTypeMeta.js
import {
  FileCheck,
  Shield,
  Camera,
  User,
  CreditCard,
  Landmark,
  BookOpen,
  FileText,
  File,
} from "lucide-react";

// ── Document type metadata ────────────────────────────────────────────────────
export const DOC_TYPE_META = {
  signed_kye: {
    label: "Signed KYE Form",
    icon: FileCheck,
    bg: "#eff6ff",
    border: "#bfdbfe",
    text: "#1d4ed8",
    dot: "#3b82f6",
    section: "kye",
  },
  bgv_form: {
    label: "BGV Form",
    icon: Shield,
    bg: "#f5f3ff",
    border: "#ddd6fe",
    text: "#6d28d9",
    dot: "#7c3aed",
    section: "hr",
  },
  email_screenshot: {
    label: "Approval Email Screenshot",
    icon: Camera,
    bg: "#f0fdf4",
    border: "#bbf7d0",
    text: "#15803d",
    dot: "#22c55e",
    section: "hr",
  },
  photo: {
    label: "Employee Photo",
    icon: User,
    bg: "#fff7ed",
    border: "#fed7aa",
    text: "#c2410c",
    dot: "#f97316",
    section: "reg",
  },
  idPhoto: {
    label: "Employee Photo",
    icon: User,
    bg: "#fff7ed",
    border: "#fed7aa",
    text: "#c2410c",
    dot: "#f97316",
    section: "reg",
  },
  id_photo: {
    label: "Employee Photo",
    icon: User,
    bg: "#fff7ed",
    border: "#fed7aa",
    text: "#c2410c",
    dot: "#f97316",
    section: "reg",
  },
  aadharCard: {
    label: "Aadhaar Card",
    icon: CreditCard,
    bg: "#fefce8",
    border: "#fde68a",
    text: "#92400e",
    dot: "#f59e0b",
    section: "reg",
  },
  aadhar_card: {
    label: "Aadhaar Card",
    icon: CreditCard,
    bg: "#fefce8",
    border: "#fde68a",
    text: "#92400e",
    dot: "#f59e0b",
    section: "reg",
  },
  panCard: {
    label: "PAN Card",
    icon: CreditCard,
    bg: "#fdf4ff",
    border: "#e9d5ff",
    text: "#7e22ce",
    dot: "#a855f7",
    section: "reg",
  },
  pan_card: {
    label: "PAN Card",
    icon: CreditCard,
    bg: "#fdf4ff",
    border: "#e9d5ff",
    text: "#7e22ce",
    dot: "#a855f7",
    section: "reg",
  },
  bankPassbook: {
    label: "Bank Passbook",
    icon: Landmark,
    bg: "#f0fdfa",
    border: "#99f6e4",
    text: "#0f766e",
    dot: "#14b8a6",
    section: "reg",
  },
  bank_passbook: {
    label: "Bank Passbook",
    icon: Landmark,
    bg: "#f0fdfa",
    border: "#99f6e4",
    text: "#0f766e",
    dot: "#14b8a6",
    section: "reg",
  },
  resume: {
    label: "Resume",
    icon: BookOpen,
    bg: "#f8fafc",
    border: "#cbd5e1",
    text: "#334155",
    dot: "#64748b",
    section: "reg",
  },
  medicalCertificate: {
    label: "Medical Certificate",
    icon: FileText,
    bg: "#fff1f2",
    border: "#fecdd3",
    text: "#be123c",
    dot: "#f43f5e",
    section: "reg",
  },
  medical_certificate: {
    label: "Medical Certificate",
    icon: FileText,
    bg: "#fff1f2",
    border: "#fecdd3",
    text: "#be123c",
    dot: "#f43f5e",
    section: "reg",
  },
  academicRecords: {
    label: "Academic Records",
    icon: BookOpen,
    bg: "#f0f9ff",
    border: "#bae6fd",
    text: "#0369a1",
    dot: "#0ea5e9",
    section: "reg",
  },
  academic_records: {
    label: "Academic Records",
    icon: BookOpen,
    bg: "#f0f9ff",
    border: "#bae6fd",
    text: "#0369a1",
    dot: "#0ea5e9",
    section: "reg",
  },
  payslip: {
    label: "Payslip",
    icon: FileText,
    bg: "#f7fee7",
    border: "#d9f99d",
    text: "#4d7c0f",
    dot: "#84cc16",
    section: "reg",
  },
  otherCertificates: {
    label: "Other Certificates",
    icon: File,
    bg: "#f9fafb",
    border: "#e5e7eb",
    text: "#374151",
    dot: "#9ca3af",
    section: "reg",
  },
  other_certificates: {
    label: "Other Certificates",
    icon: File,
    bg: "#f9fafb",
    border: "#e5e7eb",
    text: "#374151",
    dot: "#9ca3af",
    section: "reg",
  },
  farmToCli: {
    label: "Farm to CLI",
    icon: File,
    bg: "#f9fafb",
    border: "#e5e7eb",
    text: "#374151",
    dot: "#9ca3af",
    section: "reg",
  },
  farm_to_cli: {
    label: "Farm to CLI",
    icon: File,
    bg: "#f9fafb",
    border: "#e5e7eb",
    text: "#374151",
    dot: "#9ca3af",
    section: "reg",
  },
  other: {
    label: "Other Document",
    icon: File,
    bg: "#f9fafb",
    border: "#e5e7eb",
    text: "#374151",
    dot: "#9ca3af",
    section: "other",
  },
};

export const REG_DOC_LABELS = {
  photo: "Employee Photo",
  idPhoto: "Employee Photo",
  id_photo: "Employee Photo",
  aadharCard: "Aadhaar Card",
  aadhar_card: "Aadhaar Card",
  panCard: "PAN Card",
  pan_card: "PAN Card",
  bankPassbook: "Bank Passbook",
  bank_passbook: "Bank Passbook",
  resume: "Resume",
  medicalCertificate: "Medical Certificate",
  medical_certificate: "Medical Certificate",
  academicRecords: "Academic Records",
  academic_records: "Academic Records",
  payslip: "Payslip",
  otherCertificates: "Other Certificates",
  other_certificates: "Other Certificates",
  farmToCli: "Farm to CLI",
  farm_to_cli: "Farm to CLI",
};

export const HR_UPLOAD_TYPES = [
  {
    key: "bgv_form",
    label: "BGV Form",
    icon: Shield,
    accept: "image/*,application/pdf",
  },
  {
    key: "email_screenshot",
    label: "Approval Email Screenshot",
    icon: Camera,
    accept: "image/*,application/pdf",
  },
];